name: Build bootengine

on:
  push:
    branches: ["alpha"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install GO
        uses: actions/setup-go@v2
      - run: make beb
      - run: ls
      - name: Setup AWS CLI
        use:  chrislennon/action-aws-cli@v1.1
      - run: aws s3 ls
        env:  
            ACCESS_KEY: ${{ secrets.ACCESS_KEY }
            ACCESS_KEY_SECRET: ${{ secret.ACCESS_KEY_SECRET }}
            REGION: ${{ secrets.REGION }}
      - name: Push to S3
        run: aws s3 cp ./devboot s3://devboot
        env:  
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }
          ACCESS_KEY_SECRET: ${{ secret.ACCESS_KEY_SECRET }}
          REGION: ${{ secrets.REGION }}


